// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkmLhTFCofeCEt2FyXAAaTSR9SJpj5v1I',
    appId: '1:991307126024:web:1d752c5fddc2023d3a88bd',
    messagingSenderId: '991307126024',
    projectId: 'ellemoratest-a7628',
    authDomain: 'ellemoratest-a7628.firebaseapp.com',
    storageBucket: 'ellemoratest-a7628.appspot.com',
    measurementId: 'G-WR2LZ13FRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDDNcx9_BMi73_urvFY7CfYNJo3g9Ps2A',
    appId: '1:991307126024:android:dd04f95309bf20373a88bd',
    messagingSenderId: '991307126024',
    projectId: 'ellemoratest-a7628',
    storageBucket: 'ellemoratest-a7628.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh2Cs0Fyu91bg6TurIKshqgdd5yBtzDMI',
    appId: '1:991307126024:ios:dc55c85cc6a26f593a88bd',
    messagingSenderId: '991307126024',
    projectId: 'ellemoratest-a7628',
    storageBucket: 'ellemoratest-a7628.appspot.com',
    iosClientId: '991307126024-js9p5povsr171dl1ka0r0ourin42k1kg.apps.googleusercontent.com',
    iosBundleId: 'com.example.almoraTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh2Cs0Fyu91bg6TurIKshqgdd5yBtzDMI',
    appId: '1:991307126024:ios:dc55c85cc6a26f593a88bd',
    messagingSenderId: '991307126024',
    projectId: 'ellemoratest-a7628',
    storageBucket: 'ellemoratest-a7628.appspot.com',
    iosClientId: '991307126024-js9p5povsr171dl1ka0r0ourin42k1kg.apps.googleusercontent.com',
    iosBundleId: 'com.example.almoraTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkmLhTFCofeCEt2FyXAAaTSR9SJpj5v1I',
    appId: '1:991307126024:web:d56e8e6f88b4c31e3a88bd',
    messagingSenderId: '991307126024',
    projectId: 'ellemoratest-a7628',
    authDomain: 'ellemoratest-a7628.firebaseapp.com',
    storageBucket: 'ellemoratest-a7628.appspot.com',
    measurementId: 'G-GQ0CSWLYLJ',
  );
}
